# Generated by Django 2.1.2 on 2018-10-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='key',
            field=models.TextField(),
        ),
    ]
