# Generated by Django 2.1.2 on 2018-10-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20181017_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='expire_in',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='valid_in',
            field=models.CharField(default='', max_length=255),
        ),
    ]
